name: wl-pprint-annotated
version: 0.0.1.3
description: Wadler/Leijen pretty printer with annotations and slightly modernized API
synopsis: Wadler/Leijen pretty printer with annotations and slightly modernized API
category: Text
stability: experimental
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2011-2012 Edward A. Kmett, 2000 Daan Leijen
license: BSD3
github: minad/wl-pprint-annotated

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1

default-extensions:
- FlexibleInstances
- TypeSynonymInstances
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- DefaultSignatures
- OverloadedStrings

ghc-options:
- -Wall
#- -Widentities
#- -Wmonomorphism-restriction
#- -Wincomplete-uni-patterns
#- -Wincomplete-record-updates
#- -Wtabs
#- -fprint-potential-instances

dependencies:
- base       >= 4.8  && < 5
- containers >= 0.4  && < 0.6
- text       >= 0.11 && < 1.3
- deepseq    >= 1.4  && < 1.6

when:
  - condition: impl(ghc < 8.0)
    dependencies: semigroups >= 0.9 && < 1

library:
  source-dirs: src

tests:
  wl-pprint:
    main: WLPPrintTests.hs
    source-dirs: test
    dependencies:
      - wl-pprint-annotated
      - HUnit
      - test-framework
      - test-framework-hunit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
